### PR TITLE
Ch app structure

### PR DESCRIPTION
**Pull request by ifeLight**
## Description
This is like a starter code for the back-end, and we migrated from Parcel to Webpack but still using the default babel compiler. Tested on a working environment. Kindly review it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dave-ok — COMMENTED** [review]
@ifeLight Is there any particular reason why we are using webpack? We already have babel

**Comment by ifeLight** [comment]
> @ifeLight Is there any particular reason why we are using webpack? We already have babel

@dave-ok webpack is just to compile the Babel code, and webpack does it well than Babel compilers, the front end project used parcel, but parcel isn't for Node.js server project, so webpack was for it, webpack is just a bundler, while Babel is the es5 compiler

**Comment by dave-ok** [comment]
@ifeLight Webpack is meant for bundling HTML/CSS and JS for frontend, to minimize size for faster delivery time over a network and less browser memory consumption. This is a REST API server and does not need webpack

**Comment by johnebri** [comment]
@ifeLight do you use Webpack for your RESTful APIs?

**Comment by ifeLight** [comment]
> @ifeLight do you use Webpack for your RESTful APIs?

@johnebri @dave-ok I do use webpack, it was once recommended by Andela themselves on one specific programs like that, babel-node has a lot of bugs and so and it is heavy, so from them have used it a lot.

**Comment by dave-ok** [comment]
@ifeLight Babel-node is used for development not production. You build your code with babel before deployment

**Comment by ifeLight** [comment]
> @ifeLight Babel-node is used for development not production. You build your code with babel before deployment

@dave-ok have used Babel a lot, I also face running issues after compiling,  I use a Unix environment, Webpack is far okay, it's well cross-platformed

**Comment by ifeLight** [comment]
@dave-ok @johnebri you don't need to be bothered about the webpack, is just on the development and building for production which is very good at it, the setup is there, there won't be any major changes to the core  code if you want to revert back to Babel only

**Comment by dave-ok** [comment]
@ifeLight If you have issues with babel. No worries I can raise a PR that uses only babel

**Comment by dave-ok** [comment]
@ifeLight Webpack is unnecessary luggage

**Review by johnebri — APPROVED** [review]

**Comment by ifeLight** [comment]
Another duplicate has been created

**Pull request closed without merging**
